spring:
  application:
    name: zbfapi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zbfapi
    username: root
    password: 121388
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis
    timeout: 86400
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
#dubbo:
#  application:
#    name: dubbo-springboot-demo-provider
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    id: nacos-registry
yuapi:
  client:
    secret-key: zb603xny8f0xlxm793oa0vqqxqfak2ww
    access-key: sneo9hsmpl3z0vg893al530w0dunxjto
#    address: nacos://localhost:8848